[package]
name = "time_warp"
version = "0.1.0"
authors = ["davemollen <davemollen@gmail.com>"]
edition = "2021"

[dependencies]
fastrand = "2.3.0"
rubato = "0.16.2"
symphonia = { version = "0.5.4", features = ["all"] }
thiserror = "2.0.12"
